[package]
name = "qg-base"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
tokio = {version = "1.34.0", features = ["full"]}
qg-shared = {path = "../shared"}
qg-ping = {path = "../commands/ping"}
shuttle-runtime = "0.32.0"
shuttle-serenity = "0.32.0"
shuttle-secrets = "0.32.0"
tracing = "0.1.40"

[dependencies.serenity]
version = "0.11.7"
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]

# commands
quiggle-games-ping = {path = "../ping"}
